/* This file is part of Dilay
 * Copyright © 2015-2018 Alexander Bau
 * Use and redistribute under the terms of the GNU General Public License
 */
#ifndef DILAY_TOOLS
#define DILAY_TOOLS

#include "tool.hpp"
#include "tool/sculpt.hpp"

DECLARE_TOOL (ToolMoveMesh, DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_PRESS_EVENT
                              DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL (ToolRotateMesh, DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_PRESS_EVENT
                                DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL (ToolDeleteMesh, DECLARE_TOOL_RUN_RELEASE_EVENT)

DECLARE_TOOL (ToolNewMesh, DECLARE_TOOL_RUN_RENDER DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL_SCULPT (ToolSculptDraw)
DECLARE_TOOL_SCULPT (ToolSculptGrab)
DECLARE_TOOL_SCULPT (ToolSculptSmooth)
DECLARE_TOOL_SCULPT (ToolSculptFlatten)
DECLARE_TOOL_SCULPT (ToolSculptCrease)
DECLARE_TOOL_SCULPT (ToolSculptPinch)
DECLARE_TOOL_SCULPT (ToolSculptReduce)

DECLARE_TOOL (ToolEditSketch, DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_PRESS_EVENT
                                DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL (ToolDeleteSketch, DECLARE_TOOL_RUN_RELEASE_EVENT)

DECLARE_TOOL (ToolRebalanceSketch, DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL (ToolConvertSketch, DECLARE_TOOL_RUN_RELEASE_EVENT)

DECLARE_TOOL (ToolSketchSpheres,
              DECLARE_TOOL_RUN_RENDER DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_PRESS_EVENT
                DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_MOUSE_WHEEL_EVENT
                  DECLARE_TOOL_RUN_CURSOR_UPDATE DECLARE_TOOL_RUN_COMMIT
                                                 DECLARE_TOOL_RUN_FROM_CONFIG)

DECLARE_TOOL (ToolTrimMesh,
              DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_MOUSE_WHEEL_EVENT
                DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_PAINT DECLARE_TOOL_RUN_COMMIT)

DECLARE_TOOL (ToolRemesh,
              DECLARE_TOOL_RUN_MOVE_EVENT DECLARE_TOOL_RUN_PRESS_EVENT
                DECLARE_TOOL_RUN_RELEASE_EVENT DECLARE_TOOL_RUN_PAINT DECLARE_TOOL_RUN_COMMIT)

#endif
